window.FinanceApp=(()=>{
  const $=id=>document.getElementById(id);let currentPage="dashboard";let editingIncomeId=null;
  const SIDEBAR_KEY="financetrack_sidebar_hidden_v1";
  const categories=()=>FinanceStorage.getDB().settings.categories;
  function formatNumber(v){const n=String(v??"").replace(/\D/g,"");return n?new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(n)):""}
  function parseNumber(v){const n=String(v??"").replace(/\D/g,"");return Number(n)||0}
  function formatCurrency(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0)}
  function formatDate(v){if(!v)return"-";return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${v}T00:00:00`))}
  function monthLabel(k){const [y,m]=String(k).split("-");return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(Number(y),Number(m)-1,1))}
  function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function escapeAttr(v){return escapeHtml(v).replace(/`/g,"&#096;")}
  function toast(msg){const n=document.createElement("div");n.className="toast";n.textContent=msg;$("toastContainer").appendChild(n);setTimeout(()=>n.remove(),2600)}
  function setupMoney(){document.addEventListener("input",e=>{if(!e.target.classList.contains("money-input"))return;const raw=e.target.value.replace(/\D/g,"");e.target.value=raw?new Intl.NumberFormat("id-ID",{maximumFractionDigits:0}).format(Number(raw)):""})}
  function showPage(page){currentPage=page;document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${page}`));document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const titles={dashboard:"Dashboard",expenses:"Pengeluaran",budget:"Anggaran",history:"Riwayat Bulanan",reports:"Laporan",settings:"Pengaturan"};$("pageTitle").textContent=titles[page]||"Dashboard";if(page==="expenses")FinanceExpenses.render();if(page==="budget")FinanceBudget.render();if(page==="history")FinanceHistory.render();if(page==="reports")FinanceReports.render();if(page==="settings")FinanceSettings.render();if(window.innerWidth<=800)$(`sidebar`).classList.remove("open")}
  function monthSelector(){const d=FinanceStorage.getDB(),keys=Object.keys(d.months).sort((a,b)=>b.localeCompare(a));$("monthSelector").innerHTML=keys.map(k=>`<option value="${k}" ${k===d.activeMonth?"selected":""}>${monthLabel(k)}</option>`).join("")}
  function refresh(){monthSelector();FinanceDashboard.render();if(currentPage==="expenses")FinanceExpenses.refreshCategories();if(currentPage==="budget")FinanceBudget.render();if(currentPage==="history")FinanceHistory.render();if(currentPage==="reports")FinanceReports.render();if(currentPage==="settings")FinanceSettings.render();FinanceSettings.applyTheme()}
  function renderIncomeList(){const m=FinanceStorage.getDB().activeMonth,rows=FinanceStorage.listIncomes(m);$("incomeList").innerHTML=rows.length?rows.map(x=>`<div class="income-row"><div><strong>${formatDate(x.date)} · ${escapeHtml(x.source)}</strong><small>${escapeHtml(x.note||"Pemasukan")}</small></div><div class="income-row-actions"><strong>${formatCurrency(x.amount)}</strong><button type="button" class="secondary-button small-button" data-edit-income="${x.id}">Edit</button><button type="button" class="danger-button small-button" data-delete-income="${x.id}">Hapus</button></div></div>`).join(""):`<div class="empty-state">Belum ada pemasukan pada bulan ini.</div>`}
  function openIncome(id=null){editingIncomeId=id;const found=id?FinanceStorage.findIncome(id):null,today=FinanceData.dateKey(),min=FinanceData.retentionCutoff();$("incomeModalTitle").textContent=found?"Edit Pemasukan":"Tambah Pemasukan";$("incomeId").value=id||"";$("incomeDate").min=min;$("incomeDate").max=today;$("incomeDate").value=found?.item.date||today;$("incomeSource").value=found?.item.source||"Gaji";$("incomeAmount").value=found?formatNumber(found.item.amount):"";$("incomeNote").value=found?.item.note||"";renderIncomeList();$("incomeModal").classList.remove("hidden");setTimeout(()=>$(found?"incomeAmount":"incomeDate").focus(),50)}
  function closeIncome(){$("incomeModal").classList.add("hidden");editingIncomeId=null}
  function saveIncome(e){e.preventDefault();const date=$("incomeDate").value,amount=parseNumber($("incomeAmount").value),source=$("incomeSource").value.trim()||"Pemasukan",note=$("incomeNote").value.trim(),min=FinanceData.retentionCutoff(),today=FinanceData.dateKey();if(!date||date<min||date>today)return toast(`Tanggal pemasukan harus antara ${formatDate(min)} dan ${formatDate(today)}.`);if(amount<=0)return toast("Nominal pemasukan harus lebih dari 0.");const item={id:$("incomeId").value||(crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`),date,amount,source,note};if(editingIncomeId){if(!FinanceStorage.updateIncome(editingIncomeId,item))return toast("Pemasukan tidak ditemukan.")}else FinanceStorage.addIncome(item);closeIncome();refresh();toast(editingIncomeId?"Pemasukan diperbarui.":"Pemasukan berhasil ditambahkan.")}
  function bind(){
    document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll("[data-page-link]").forEach(b=>b.onclick=()=>showPage(b.dataset.pageLink));$("monthSelector").onchange=()=>{FinanceStorage.setActiveMonth($("monthSelector").value);refresh()};$("quickAddButton").onclick=()=>FinanceExpenses.open();$("addExpenseButton").onclick=()=>FinanceExpenses.open();$("saveBudgetButton").onclick=()=>FinanceBudget.save();$("createMonthButton").onclick=()=>FinanceHistory.createMonth();$("exportCsvButton").onclick=()=>FinanceReports.csv();$("downloadPdfButton").onclick=()=>FinanceReports.downloadPdf();$("statIncome").ondblclick=()=>openIncome();$("manageIncomeButton").onclick=()=>openIncome();
    $("closeIncomeModal").onclick=closeIncome;$("cancelIncomeButton").onclick=closeIncome;$("incomeForm").onsubmit=saveIncome;$("incomeList").onclick=e=>{const edit=e.target.closest("[data-edit-income]"),del=e.target.closest("[data-delete-income]");if(edit)openIncome(edit.dataset.editIncome);if(del){if(confirm("Hapus pemasukan ini?")){FinanceStorage.deleteIncome(del.dataset.deleteIncome);renderIncomeList();refresh();toast("Pemasukan dihapus.")}}};
    const sidebar=$("sidebar"),sidebarToggle=$("sidebarToggle");
    const updateSidebarButton=(visible)=>{sidebarToggle.setAttribute("aria-expanded",String(visible));sidebarToggle.setAttribute("aria-label",visible?"Sembunyikan panel navigasi":"Tampilkan panel navigasi");sidebarToggle.title=visible?"Sembunyikan panel navigasi":"Tampilkan panel navigasi"};
    const applySidebarState=()=>{if(window.innerWidth<=800){sidebar.classList.remove("sidebar-hidden");sidebar.classList.remove("open");updateSidebarButton(false);return}const hidden=localStorage.getItem(SIDEBAR_KEY)==="1";sidebar.classList.toggle("sidebar-hidden",hidden);updateSidebarButton(!hidden)};
    sidebarToggle.onclick=()=>{if(window.innerWidth<=800){const open=sidebar.classList.toggle("open");sidebar.classList.remove("sidebar-hidden");updateSidebarButton(open);return}const hidden=!sidebar.classList.contains("sidebar-hidden");sidebar.classList.toggle("sidebar-hidden",hidden);localStorage.setItem(SIDEBAR_KEY,hidden?"1":"0");updateSidebarButton(!hidden)};applySidebarState();setupMoney();FinanceExpenses.bind();FinanceSettings.bind()
  }
  function init(){FinanceStorage.load();bind();refresh();showPage("dashboard")}
  window.addEventListener("resize",()=>{const sidebar=$("sidebar");if(window.innerWidth<=800){sidebar.classList.remove("sidebar-hidden");sidebar.classList.remove("open")}else{sidebar.classList.remove("open");sidebar.classList.toggle("sidebar-hidden",localStorage.getItem(SIDEBAR_KEY)==="1")}});
  return{init,refresh,showPage,formatNumber,parseNumber,formatCurrency,formatDate,monthLabel,escapeHtml,escapeAttr,toast,categories};
})();document.addEventListener("DOMContentLoaded",FinanceApp.init);