window.FinanceDashboard=(()=>{
  const $=id=>document.getElementById(id),sum=m=>m.expenses.reduce((s,x)=>s+Number(x.amount||0),0);
  function statusInfo(m){const t=FinanceStorage.monthTotals(m.key),i=t.income,e=t.expense,b=t.balance,target=Number(m.savingTarget)||0;if(!i&&!e&&!t.opening&&!target)return{label:"BELUM ADA DATA",text:"Tambahkan pemasukan dan pengeluaran untuk melihat kondisi keuangan."};if(b<0)return{label:"DEFISIT",text:"Saldo berjalan bernilai negatif setelah memperhitungkan saldo awal, pemasukan, dan pengeluaran."};if(target>0&&t.net>=target)return{label:"TARGET TERCAPAI",text:"Peningkatan saldo bulan ini sudah memenuhi target tabungan."};if(i&&e/i<=.65)return{label:"HEMAT",text:"Pengeluaran masih berada pada tingkat yang relatif rendah terhadap pemasukan bulan ini."};if(i&&e/i<=.85)return{label:"TERKENDALI",text:"Pengeluaran masih berada dalam rentang yang cukup terkendali terhadap pemasukan bulan ini."};return{label:"PERLU KONTROL",text:"Porsi pengeluaran sudah cukup tinggi dibandingkan pemasukan bulan ini."}}
  function render(){const m=FinanceStorage.getMonth(),t=FinanceStorage.monthTotals(m.key),e=t.expense,b=t.balance,info=statusInfo(m),cats=FinanceApp.categories();
    $("statIncome").textContent=FinanceApp.formatCurrency(t.income);$("statExpense").textContent=FinanceApp.formatCurrency(e);$("statBalance").textContent=FinanceApp.formatCurrency(b);$("statSaving").textContent=FinanceApp.formatCurrency(m.savingTarget);$("financialStatus").textContent=info.label;$("financialStatusText").textContent=info.text;
    const balanceNote=$("balanceNote");if(balanceNote)balanceNote.textContent=`Saldo awal ${FinanceApp.formatCurrency(t.opening)} · Perubahan bulan ${FinanceApp.formatCurrency(t.net)}`;
    const groups=Object.keys(cats).map(group=>({group,amount:m.expenses.filter(x=>x.group===group).reduce((s,x)=>s+Number(x.amount||0),0)})),max=Math.max(1,...groups.map(x=>x.amount));
    $("groupChart").innerHTML=groups.map(x=>`<div class="bar-row"><div class="bar-meta"><span>${FinanceApp.escapeHtml(x.group)}</span><strong>${FinanceApp.formatCurrency(x.amount)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,x.amount/max*100)}%"></div></div></div>`).join("")||`<div class="empty-state">Belum ada kelompok.</div>`;
    const items=groups.map(g=>{const planned=(cats[g.group]||[]).reduce((s,c)=>s+Number(m.budgets[c]||0),0);return {...g,planned}}).filter(x=>x.planned||x.amount);
    $("budgetOverview").innerHTML=items.length?items.map(x=>{const pct=x.planned?x.amount/x.planned*100:0;return `<div class="budget-row"><div class="budget-row-head"><span>${FinanceApp.escapeHtml(x.group)}</span><span>${FinanceApp.formatCurrency(x.amount)} / ${FinanceApp.formatCurrency(x.planned)}</span></div><div class="progress"><span class="${pct>100?"over":""}" style="width:${Math.min(100,Math.max(2,pct))}%"></span></div></div>`}).join(""):`<div class="empty-state">Belum ada rencana atau transaksi.</div>`;
    const recent=[...m.expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$("recentTransactions").innerHTML=recent.length?recent.map(x=>`<tr><td>${FinanceApp.formatDate(x.date)}</td><td>${FinanceApp.escapeHtml(x.group)}</td><td>${FinanceApp.escapeHtml(x.category)}</td><td>${FinanceApp.escapeHtml(x.note||"-")}</td><td><strong>${FinanceApp.formatCurrency(x.amount)}</strong></td></tr>`).join(""):`<tr><td colspan="5" class="empty-state">Belum ada transaksi bulan ini.</td></tr>`;
    const highest=[...m.expenses].sort((a,b)=>b.amount-a.amount)[0],ratio=t.income?e/t.income*100:0;$("dashboardInsights").innerHTML=`<div class="insight-item"><span>Saldo awal</span><strong>${FinanceApp.formatCurrency(t.opening)}</strong></div><div class="insight-item"><span>Perubahan bersih bulan ini</span><strong class="${t.net<0?"negative":"positive"}">${FinanceApp.formatCurrency(t.net)}</strong></div><div class="insight-item"><span>Rasio pengeluaran / pemasukan</span><strong>${t.income?ratio.toFixed(1)+"%":"—"}</strong></div><div class="insight-item"><span>Pengeluaran terbesar</span><strong>${highest?FinanceApp.formatCurrency(highest.amount):"—"}</strong><small>${highest?FinanceApp.escapeHtml(highest.category):"Belum ada"}</small></div>`;
    const incomes=FinanceStorage.listIncomes(m.key);const incomeList=$("dashboardIncomeList");if(incomeList)incomeList.innerHTML=incomes.length?incomes.slice(0,5).map(x=>`<div class="income-mini-row"><span>${FinanceApp.formatDate(x.date)} · ${FinanceApp.escapeHtml(x.source)}</span><strong>${FinanceApp.formatCurrency(x.amount)}</strong></div>`).join(""):`<div class="empty-mini">Belum ada pemasukan pada bulan ini.</div>`;
  }
  return {render,statusInfo};
})();