window.FinanceReports=(()=>{
  const $=id=>document.getElementById(id);
  const groupColors=["#2563eb","#7c3aed","#16a34a","#d97706","#dc2626","#0891b2"];
  const toNumber=v=>Number(v)||0;
  const downloadStamp=()=>new Date();
  const formatDateTime=d=>new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d);
  const formatDateLong=v=>new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00`));
  function makeReport(){
    const d=FinanceStorage.getDB(),m=FinanceStorage.getMonth(),cats=d.settings.categories||{},totals=FinanceStorage.monthTotals(m.key);
    const expenses=Array.isArray(m.expenses)?m.expenses.map(x=>({...x,amount:toNumber(x.amount)})):[];
    const income=totals.income,expense=totals.expense,balance=totals.balance,monthlyNet=totals.net;
    const actualSaving=Math.max(0,monthlyNet),info=FinanceDashboard.statusInfo(m),generatedAt=downloadStamp();
    const groups=Object.entries(cats).map(([group,items],i)=>{const planned=items.reduce((s,c)=>s+toNumber(m.budgets?.[c]),0),actual=expenses.filter(x=>x.group===group).reduce((s,x)=>s+x.amount,0),difference=planned-actual,pct=planned?actual/planned*100:null,details=items.map(category=>{const plannedAmount=toNumber(m.budgets?.[category]),actualAmount=expenses.filter(x=>x.group===group&&x.category===category).reduce((s,x)=>s+x.amount,0);return{category,planned:plannedAmount,actual:actualAmount,difference:plannedAmount-actualAmount,pct:plannedAmount?actualAmount/plannedAmount*100:null}});return{group,items,planned,actual,difference,pct,color:groupColors[i%groupColors.length],details}});
    const categories=Object.entries(cats).flatMap(([group,items])=>items.map(category=>({group,category,amount:expenses.filter(e=>e.group===group&&e.category===category).reduce((s,e)=>s+e.amount,0)}))).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount);
    const plannedTotal=groups.reduce((s,g)=>s+g.planned,0),difference=plannedTotal-expense,plannedDetails=groups.flatMap(g=>g.details.map(x=>({...x,group:g.group,color:g.color})));
    const dayMap=new Map();expenses.forEach(x=>{const key=x.date||"0000-00-00";if(!dayMap.has(key))dayMap.set(key,[]);dayMap.get(key).push(x)});
    const dailyActual=[...dayMap.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([date,items])=>({date,items:items.slice().sort((a,b)=>String(b.id||"").localeCompare(String(a.id||""))),total:items.reduce((s,x)=>s+x.amount,0)}));
    const monthlyIncomes=FinanceStorage.listIncomes(m.key);
    let conclusion=info.text+` Saldo awal bulan ${FinanceApp.formatCurrency(totals.opening)} ditambah pemasukan ${FinanceApp.formatCurrency(income)} dan dikurangi pengeluaran ${FinanceApp.formatCurrency(expense)} menghasilkan saldo akhir ${FinanceApp.formatCurrency(balance)}.`;
    if(plannedTotal>0){conclusion+=difference>=0?` Total pengeluaran aktual masih ${FinanceApp.formatCurrency(difference)} di bawah rencana pengeluaran.`:` Total pengeluaran aktual telah melampaui rencana sebesar ${FinanceApp.formatCurrency(Math.abs(difference))}.`;const over=groups.filter(x=>x.difference<0);if(over.length)conclusion+=` Kelompok yang melebihi rencana: ${over.map(x=>`${x.group} (${FinanceApp.formatCurrency(Math.abs(x.difference))})`).join(", ")}.`;else conclusion+=` Tidak ada kelompok yang melampaui rencana pengeluaran.`}else conclusion+=` Belum ada rencana pengeluaran yang ditetapkan pada bulan ini, sehingga perbandingan rencana dan aktual belum dapat dihitung.`;
    if(categories[0])conclusion+=` Pengeluaran aktual terbesar berasal dari ${categories[0].category} (${categories[0].group}) sebesar ${FinanceApp.formatCurrency(categories[0].amount)}.`;
    return{monthKey:m.key,monthLabel:FinanceApp.monthLabel(m.key),appName:d.settings.appName||"FinanceTrack",userName:d.settings.userName||"-",income,expense,balance,openingBalance:totals.opening,monthlyNet,savingTarget:toNumber(m.savingTarget),actualSaving,status:info.label,conclusion,plannedTotal,difference,groups,categories,plannedDetails,dailyActual,incomes:monthlyIncomes,downloadedAt:generatedAt,downloadDateLabel:formatDateTime(generatedAt)};
  }
  function render(){const r=makeReport();$("reportMonthTitle").textContent=`Laporan Keuangan Bulanan · ${r.monthLabel}`;$("reportUserLabel").innerHTML=`Pengguna: ${FinanceApp.escapeHtml(r.userName)}<div class="report-download-date">Dibuat/diunduh: ${FinanceApp.escapeHtml(r.downloadDateLabel)}</div>`;$("reportStatus").textContent=r.status;$("reportSummary").innerHTML=[["Saldo Awal",r.openingBalance],["Pemasukan / Gaji",r.income],["Pengeluaran Aktual",r.expense],["Saldo Akhir",r.balance]].map(x=>`<div class="report-stat"><span>${x[0]}</span><strong>${FinanceApp.formatCurrency(x[1])}</strong></div>`).join("");
    $("reportGroups").innerHTML=r.groups.length?r.groups.map(x=>`<div class="group-report-card" style="--group-color:${x.color}"><h4>${FinanceApp.escapeHtml(x.group)}</h4><div class="metric-line"><span>Rencana</span><strong>${FinanceApp.formatCurrency(x.planned)}</strong></div><div class="metric-line"><span>Aktual</span><strong>${FinanceApp.formatCurrency(x.actual)}</strong></div><div class="metric-line"><span>Selisih</span><strong class="${x.difference<0?"negative":"positive"}">${x.difference<0?"− ":"+ "}${FinanceApp.formatCurrency(Math.abs(x.difference))}</strong></div><div class="metric-line"><span>Realisasi</span><strong>${x.pct===null?"—":x.pct.toFixed(1)+"%"}</strong></div></div>`).join(""):`<div class="empty-state">Belum ada kelompok.</div>`;
    $("reportPlannedDetail").innerHTML=`<div class="report-detail-row header"><span>Kelompok / Sub-kategori</span><span class="amount">Rencana</span><span class="amount">Aktual</span><span class="amount">Selisih</span></div>`+(r.plannedDetails.length?r.plannedDetails.map(x=>`<div class="report-detail-row"><span><strong>${FinanceApp.escapeHtml(x.group)}</strong> · ${FinanceApp.escapeHtml(x.category)}</span><span class="amount">${FinanceApp.formatCurrency(x.planned)}</span><span class="amount">${FinanceApp.formatCurrency(x.actual)}</span><span class="amount ${x.difference<0?"negative":"positive"}">${x.difference<0?"− ":"+ "}${FinanceApp.formatCurrency(Math.abs(x.difference))}</span></div>`).join(""):"<div class=\"empty-state\">Belum ada sub-kategori.</div>");
    $("reportDailyActual").innerHTML=r.dailyActual.length?r.dailyActual.map(day=>`<div class="report-day-block"><div class="report-day-head"><span>${FinanceApp.escapeHtml(formatDateLong(day.date))}</span><strong>${FinanceApp.formatCurrency(day.total)}</strong></div>${day.items.map(x=>`<div class="report-day-item"><div><strong>${FinanceApp.escapeHtml(x.category)}</strong><small>${FinanceApp.escapeHtml(x.group)}${x.note?` · ${FinanceApp.escapeHtml(x.note)}`:""}</small></div><strong>${FinanceApp.formatCurrency(x.amount)}</strong></div>`).join("")}</div>`).join(""):"<div class=\"empty-state\">Belum ada pengeluaran aktual yang dicatat.</div>";
    $("reportRecap").innerHTML=[["Saldo Awal",r.openingBalance],["Total Gaji / Pemasukan",r.income],["Total Rencana",r.plannedTotal],["Total Aktual",r.expense],[r.difference>=0?"Sisa Rencana":"Kelebihan dari Rencana",Math.abs(r.difference)],["Saldo Akhir",r.balance]].map(x=>`<div class="report-recap-card"><span>${x[0]}</span><strong>${FinanceApp.formatCurrency(x[1])}</strong></div>`).join("");
    $("reportCategories").innerHTML=r.categories.length?r.categories.map(x=>`<div class="metric-line"><span>${FinanceApp.escapeHtml(x.group)} · ${FinanceApp.escapeHtml(x.category)}</span><strong>${FinanceApp.formatCurrency(x.amount)}</strong></div>`).join(""):"<div class=\"empty-state\">Belum ada pengeluaran.</div>";
    $("reportConclusion").innerHTML=`<p>${FinanceApp.escapeHtml(r.conclusion)}</p><p><strong>Korelasi arus kas:</strong> saldo akhir = saldo awal + pemasukan − pengeluaran. Sistem menentukan bulan transaksi dari tanggal yang Anda input.</p><p><strong>Tanggal laporan:</strong> ${FinanceApp.escapeHtml(r.downloadDateLabel)}</p>`;
  }
  function csv(){const m=FinanceStorage.getMonth(),rows=[["Tanggal","Jenis","Kelompok","Kategori/Sumber","Catatan","Nominal"],...FinanceStorage.listIncomes(m.key).map(x=>[x.date,"Pemasukan","",x.source,x.note||"",x.amount]),...m.expenses.map(x=>[x.date,"Pengeluaran",x.group,x.category,x.note||"",x.amount])],csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`FinanceTrack-${m.key}.csv`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
  function downloadPdf(){const report=makeReport(),ok=FinancePDF.downloadReport(report);FinanceApp.toast(ok?"PDF berhasil dibuat dan diunduh.":"PDF gagal dibuat. Silakan periksa Console browser.")}
  return{render,csv,downloadPdf,makeReport};
})();